import XCTest
@testable import Cypriot_Keyboard

class PhoneticFolderTests: XCTestCase {

    private var folder: PhoneticFolder!

    override func setUpWithError() throws {
        let bundle = Bundle(for: type(of: self))
        guard let url = bundle.url(forResource: "phonetic_fold", withExtension: "json") else {
            XCTFail("phonetic_fold.json not in test bundle")
            return
        }
        let data = try Data(contentsOf: url)
        self.folder = try PhoneticFolder(jsonData: data)
    }

    func testEmptyInput() {
        XCTAssertEqual(folder.fold(""), "")
    }

    func testIClassCollapse() {
        XCTAssertEqual(folder.fold("καλημερα"), "καλıμeρα")
        XCTAssertEqual(folder.fold("καλιμερα"), "καλıμeρα")
        XCTAssertEqual(folder.fold("καλυμερα"), "καλıμeρα")
    }

    func testDigraphsWinOverSingles() {
        XCTAssertEqual(folder.fold("ειδος"), "ıδoσ")
        XCTAssertEqual(folder.fold("οικος"), "ıκoσ")
        XCTAssertEqual(folder.fold("αιμα"), "eμα")
    }

    func testDiacriticsDrop() {
        XCTAssertEqual(folder.fold("καλημέρα"), "καλıμeρα")
        XCTAssertEqual(folder.fold("ώρα"), "oρα")
    }

    func testFinalSigma() {
        XCTAssertEqual(folder.fold("καλος"), "καλoσ")
        XCTAssertEqual(folder.fold("καλός"), "καλoσ")
    }

    func testPassesThroughUnmapped() {
        XCTAssertEqual(folder.fold("hello"), "hello")
        XCTAssertEqual(folder.fold(" "), " ")
    }

    // MARK: - foldVariants (multi-fold)

    func testFoldVariantsNoDigraphReturnsSingle() {
        // "καλος" has only single-char rules in play; one variant.
        let variants = folder.foldVariants("καλος")
        XCTAssertEqual(variants, ["καλoσ"])
    }

    func testFoldVariantsBranchesAtDigraph() {
        // "νοιμα" matches the οι→ı digraph at position 1 AND the ο→o single
        // rule at the same position. Two branches expected: νoıμα and νoıμα
        // (with ι→ı as a separate fold step). Both must collapse i-class
        // vowels but the difference is whether the ο is folded standalone
        // or absorbed into the οι digraph.
        let variants = folder.foldVariants("νοιμα")
        // The "νοιμα" → οι→ı path: ν + ı + μ + α  = "νıμα"
        // The "νοιμα" → ο→o, ι→ı path:  ν + o + ı + μ + α = "νoıμα"
        XCTAssertEqual(variants.count, 2)
        XCTAssertTrue(variants.contains("νıμα"), "expected digraph fold νıμα in \(variants)")
        XCTAssertTrue(variants.contains("νoıμα"), "expected single-char fold νoıμα in \(variants)")
    }

    func testFoldVariantsPrimaryMatchesFold() {
        // First variant emitted should match the greedy `fold` output —
        // we walk the digraph branch first.
        let variants = folder.foldVariants("νοιμα")
        XCTAssertEqual(variants.first, folder.fold("νοιμα"))
    }

    func testFoldVariantsRespectsMaxCap() {
        // Stack multiple digraph positions; the cap limits the explosion.
        // "οιοιοι" has three οι positions → 2^3 = 8 variants without a cap.
        let capped = folder.foldVariants("οιοιοι", maxVariants: 3)
        XCTAssertEqual(capped.count, 3)
    }

    func testFoldVariantsDedupes() {
        // For "καλος" (no digraphs), there's only ever one variant — even if
        // the algorithm explored multiple paths, dedup must produce a single
        // entry.
        let variants = folder.foldVariants("καλος")
        XCTAssertEqual(Set(variants).count, variants.count)
    }

    func testCorpusParityWithPython() throws {
        // Load the parity corpus generated by Python and assert each pair
        // produces the same fold output.
        let bundle = Bundle(for: type(of: self))
        guard let url = bundle.url(forResource: "fold_corpus", withExtension: "json") else {
            XCTFail("fold_corpus.json not in test bundle")
            return
        }
        struct Pair: Decodable { let input: String; let expected: String }
        struct Corpus: Decodable { let pairs: [Pair] }
        let corpus = try JSONDecoder().decode(Corpus.self, from: Data(contentsOf: url))
        for p in corpus.pairs {
            XCTAssertEqual(folder.fold(p.input), p.expected,
                           "fold parity broke for input=\(p.input)")
        }
    }
}
