import XCTest
@testable import Cypriot_Keyboard

class PhoneticFolderTests: XCTestCase {

    private var folder: PhoneticFolder!

    override func setUpWithError() throws {
        let bundle = Bundle(for: type(of: self))
        guard let url = bundle.url(forResource: "phonetic_fold", withExtension: "json") else {
            XCTFail("phonetic_fold.json not in test bundle")
            return
        }
        let data = try Data(contentsOf: url)
        self.folder = try PhoneticFolder(jsonData: data)
    }

    func testEmptyInput() {
        XCTAssertEqual(folder.fold(""), "")
    }

    func testIClassCollapse() {
        XCTAssertEqual(folder.fold("καλημερα"), "καλıμeρα")
        XCTAssertEqual(folder.fold("καλιμερα"), "καλıμeρα")
        XCTAssertEqual(folder.fold("καλυμερα"), "καλıμeρα")
    }

    func testDigraphsWinOverSingles() {
        XCTAssertEqual(folder.fold("ειδος"), "ıδoσ")
        XCTAssertEqual(folder.fold("οικος"), "ıκoσ")
        XCTAssertEqual(folder.fold("αιμα"), "eμα")
    }

    func testDiacriticsDrop() {
        XCTAssertEqual(folder.fold("καλημέρα"), "καλıμeρα")
        XCTAssertEqual(folder.fold("ώρα"), "oρα")
    }

    func testFinalSigma() {
        XCTAssertEqual(folder.fold("καλος"), "καλoσ")
        XCTAssertEqual(folder.fold("καλός"), "καλoσ")
    }

    func testPassesThroughUnmapped() {
        XCTAssertEqual(folder.fold("hello"), "hello")
        XCTAssertEqual(folder.fold(" "), " ")
    }

    func testCorpusParityWithPython() throws {
        // Load the parity corpus generated by Python and assert each pair
        // produces the same fold output.
        let bundle = Bundle(for: type(of: self))
        guard let url = bundle.url(forResource: "fold_corpus", withExtension: "json") else {
            XCTFail("fold_corpus.json not in test bundle")
            return
        }
        struct Pair: Decodable { let input: String; let expected: String }
        struct Corpus: Decodable { let pairs: [Pair] }
        let corpus = try JSONDecoder().decode(Corpus.self, from: Data(contentsOf: url))
        for p in corpus.pairs {
            XCTAssertEqual(folder.fold(p.input), p.expected,
                           "fold parity broke for input=\(p.input)")
        }
    }
}
